all:
	javac Test.java
	java Test
	rm Test.class
	rm non_visual.class
	rm playable.class
	rm non_playable.class
	rm visual.class
	rm entry.class
	rm audio_entry.class
	rm video_entry.class
	rm image_entry.class
	rm text_entry.class
	rm dataset.class
	rm viewer.class
	rm player.class
	rm observer.class
